project:
  type: manuscript
  preview: 
    port: 4001

manuscript:
  article: index.qmd
  resources:
    - files/references.bib
    - files/references.qmd

format:
  html:
    comments:
      hypothesis: true
  latex:
    cite-method: natbib
    include-in-header: 
      - text: |
          \usepackage{wrapfig}
          \usepackage{sidecap}
          \usepackage{pdfpages}

bibliography: 
  - files/bibexport.bib
  - files/addon.bib
  - files/references.bib
  - files/bibliography/research.bib
  # - files/full.bib

execute:
  freeze: true
