project:
  type: manuscript

manuscript:
  article: index.qmd
  notebooks:
    - notebook: notebooks/00_orbits.ipynb
    - notebook: notebooks/01_ids_example.ipynb
    - notebook: notebooks/02_ids_detection.ipynb

format:
  html: default
  # pdf: default
  typst: default

bibliography: files/references.bib

execute:
  freeze: true
