project:
  type: manuscript
  preview: 
    port: 4001

manuscript:
  article: index.qmd
  resources:
    - files/references.bib
    - files/references.qmd
  notebooks:
    - notebook: comps/05_cv_Zijin.qmd
    - notebook: notebooks/00_orbits.ipynb
    - notebook: notebooks/01_ids_example.ipynb
    - notebook: notebooks/02_ids_detection.ipynb

format:
  html:
    comments:
      hypothesis: true
  latex: default
  # pdf:
    # keep-tex: true
  # typst: default

bibliography: files/references.bib

execute:
  freeze: true
