project:
  type: manuscript
  preview: 
    port: 4001

manuscript:
  article: index.qmd
  resources:
    - files/references.bib
    - files/references.qmd

format:
  html:
    comments:
      hypothesis: true
  pdf:
    cite-method: natbib
    keep-tex: true
    include-in-header: 
      - text: |
          \usepackage{wrapfig}
          \usepackage{sidecap}
  # pdf:
  #   keep-tex: true
  # typst: default

bibliography: 
  - files/bibexport.bib
  - files/bibliography/addon_zijin.bib
  - files/references.bib
  - files/addon.bib
  # - files/full.bib

execute:
  freeze: true
