project:
  type: manuscript
  preview: 
    port: 4001

manuscript:
  article: index.qmd
  notebooks:
    - notebook: notebooks/00_orbits.ipynb
    - notebook: notebooks/01_ids_example.ipynb
    - notebook: notebooks/02_ids_detection.ipynb

format:
  html:
    comments:
      hypothesis: true
  # pdf: default
  typst: default

bibliography: files/references.bib

execute:
  freeze: true
