---
title: Solar wind discontinuity propagation in the inner and outer heliosphere
subtitle: FINESST23 Proposal
authors:
  - name: Zijin Zhang
    email: zijin@ucla.edu
    orcid: 0000-0002-9968-067X
    affiliation: University of California, Los Angeles
    roles: writing
    corresponding: true
  - name: Anton V. Artemyev
    email: aartemyev@igpp.ucla.edu
    orcid: 0000-0001-8823-4474
    affiliation: University of California, Los Angeles
  - name: Vassilis Angelopoulos
    orcid: 0000-0001-7024-1561
    affiliation: University of California, Los Angeles
  - name: Xiaofei Shi
    orcid: 0000-0003-3367-5074
    affiliation: University of California, Los Angeles
  - name: Ivan Vasko
    orcid: 0000-0002-4974-4786
    affiliation: University of California, Berkeley
date: last-modified
code-links: 
  - repo
  - href: https://www.overleaf.com/project/656949cbd97a7857413f247c
    text: Overleaf
  - href: https://typst.app/project/rcdOBrTQmyYMywRvZtZvlQ
    text: Typst
wrap: preserve
---

::: {.content-visible when-format="html"}
# Background

{{< include sections/_00_background.qmd >}}
{{< pagebreak >}}
:::

\noindent{\large{\textbf{
  Solar wind discontinuity propagation in the inner and outer heliosphere
}}}

```{=latex}
\begin{center}
  \textbf{PI}: Vassilis Angelopoulos (UCLA)  \textbf{FI}: Zijin Zhang (UCLA)
\end{center}
```

# Scientific/Technical/Management

{{< include sections/_01_science.qmd >}}
{{< pagebreak >}}

# References and Acknowledgements

::: {#refs}
:::

**Acknowledgement**: This proposal is the work of the FI (Zijin Zhang). PI (Vassilis Angelopoulos) and group members (Dr. A. Artemyev, Dr. Chen Shi) provide editorial support (clarity and structure).

{{< pagebreak >}}

# Open Science and Data Management Plan (OSDMP)

{{< include sections/info/_03_osdmp.qmd >}}
{{< include sections/_03_osdmp.qmd >}}
{{< pagebreak >}}

# Research Readiness Statement

{{< include sections/info/_04_rrs.qmd >}}
{{< include sections/_04_rrs.qmd >}} 
{{< pagebreak >}}

::: {.content-visible when-format="html"}
# Curriculum Vitae (CVs)
{{< include sections/info/_05_cv.qmd >}}
:::

::: {.content-visible when-format="pdf"}
\includepdf[pages=1,pagecommand={\section{Curriculum Vitae (CVs)}\subsection{CV for Principle Investigator}}, offset=0 -1cm, width=\textwidth]{files/cv/Angelopoulos_2pgCV_January_2024_cropped.pdf}
\includepdf[pages=2, offset=0 -1cm, width=\textwidth]{files/cv/Angelopoulos_2pgCV_January_2024_cropped.pdf}
\includepdf[pagecommand={\subsection{CV for Future Investigator}}, offset=0 -0.5cm,width=1\textwidth]{files/cv/cv_Zijin_clean_cropped.pdf}
:::
{{< pagebreak >}}


::: {.content-visible when-format="html"}
# Current and Pending Support
{{< include sections/info/_06_support.qmd >}}
:::

::: {.content-visible when-format="pdf"}
\includepdf[pages=1, pagecommand={\section{Current and Pending Support}\subsection{Support Statement for PI}}, width=\textwidth, offset=0 -1.1cm]{files/support/Angelopoulos NASA Current_And_Pending__Work_Effort 3_0_0 2024-02-01_cropped.pdf}
\includepdf[pages=2, pagecommand={},width=\textwidth]{files/support/Angelopoulos NASA Current_And_Pending__Work_Effort 3_0_0 2024-02-01_cropped.pdf}

\includepdf[pages=-, pagecommand={\subsection{Support Statement for FI}},width=1.2\textwidth, offset=0 -0.5cm]{sections/Zhang NASA Current_And_Pending__Work_Effort 3_0_0 2024-01-19.pdf}
:::

::: {.content-visible when-format="html"}
# Statements of Commitment and Letters of Resource Support
:::
{{< include sections/info/_07_commitment.qmd >}}


# Mentoring Plan or Agreement

{{< include sections/info/_08_mentoring.qmd >}}
{{< include sections/_08_mentoring.qmd >}}
{{< pagebreak >}}

::: {.content-visible when-format="html"}
# Budget Narrative (Budget Justification)

{{< include sections/info/_09_budget.qmd >}}
:::

::: {.content-visible when-format="pdf"}
\includepdf[pages=-, pagecommand={\section{Budget and Narrative}},offset=0 -1cm, width=1.2\textwidth]{sections/2025 finesst budget.pdf}
:::
